### ISSUE TITLE
Coverage report disappeared

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#1386]
PRs used to have a nice coverage report: https://github.com/glacambre/firenvim/runs/5299711316

They don't anymore:
https://github.com/glacambre/firenvim/runs/7344608399?check_suite_focus=true
```
Run glacambre/action-compare-coverage@master
(node:4545) UnhandledPromiseRejectionWarning: Error: No artifact found with name master-coverage
    at main (/home/runner/work/_actions/glacambre/action-compare-coverage/master/main.js:73:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4545) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This might be because the master coverage artifact was too old and expired. In these cases, the coverage report should be uploaded anyway, it's okay if it can't be compared with master. I should also check if I can extend the lifetime of the master coverage report.

**Comment by glacambre** [comment]
Fixed in https://github.com/glacambre/action-compare-coverage/commit/55d4a666c183416edfc99d9daf73ac3f00402b1a
