### ISSUE TITLE
e.id.match is not a function (NIRVANA HQ)

### ISSUE THREAD

**Issue by raphael-ratepay** [glacambre/firenvim#1570]
- OS Version: MacOS 14.0 (23A344)
- Browser Version: Arc 1.15.2
- Browser Addon Version: 0.2.15
- Neovim Plugin Version: master (#138424d)

### What I tried to do

Start firenvim in NirvanaHQ ToDos

### What happened

The text area flickers, but nothing happens. 
The developer tools show the following error

```
chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:6714 error: e.id.match is not a function     at wrappedsendmessagecallback (chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:1482:18) (anonymous) @ chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:6714 promise.then (async) (anonymous) @ chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:6548 (anonymous) @ chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:6720 (anonymous) @ chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:6722 chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:1482 uncaught (in promise) error: e.id.match is not a function     at wrappedsendmessagecallback (chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:1482:18) wrappedsendmessagecallback @ chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:1482 chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:4873 unhandled page request: {args: array(1), funcname: array(1)} (anonymous) @ chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:4873 onmessage @ chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/index.js:1410
```

Works fine on other pages (for example here)

**Comment by raphael-ratepay** [comment]
Any update or insight on this?

**Comment by glacambre** [comment]
Nope. I don't have access to a MacOS nor to the Arc browser, so I have not tried to reproduce it. Moreover I will likely have to rewrite all of Firenvim due to https://github.com/glacambre/firenvim/issues/1193 , so I'm not terribly motivated to investigate bugs for now :)
